---
- name: Install httpd
  yum:
    name: httpd
    state: latest

- name: Configure Proxy
  copy:
    src: proxy.conf
    dest: /etc/httpd/conf.d/proxy.conf

- name: Start and enable httpd service
  systemd:
    name: httpd
    state: started
    enabled: yes
