---
- name: Install httpd
  yum:
    name: httpd
    state: latest

- name: Configure Proxy
  copy:
    src: proxy.conf
    dest: /etc/httpd/conf.d/proxy.conf
  notify:
    - start httpd

- name: Deploy application
  get_url:
    url: https://s3-us-west-2.amazonaws.com/studentapi-cit/index.html
    dest: /var/www/html

