-
  name: ignore erros
  hosts: all
  gather_facts: true
  tasks:
    - name: print OS 1
      debug:
        msg: "CentOS"
      when: ansible_distribution == "CentOS"

   - name: print OS 2
      debug:
        msg: "CentOS"
      when: ansible_distribution == "CentOS" and ansible_os_family == "RedHat"

    - name: print OS 3
      debug:
        msg: "CentOS"
      when: ansible_distribution == "ubuntu" and ansible_os_family == "RedHat"

    - name: print OS 4
      debug:
        msg: "CentOS"
      when: ansible_distribution == "CentOS" or ansible_os_family == "Ubuntu"
      

    - name: print OS 5
      debug:
        msg: "Ubuntu"
      when: ansible_distribution == "Ubuntu"
  
   
  