---
- name: ignore errors
  hosts: all
  gather_facts: true
  tasks:
    - name: print OS 1
      debug:
        msg: "CentOS"
      when: ansible_distribution == "CentOS"

    - name: print OS 2
      debug:
        msg: "RedHat Family (CentOS)"
      when: ansible_distribution == "CentOS" and ansible_os_family == "RedHat"

    - name: print OS 3
      debug:
        msg: "Ubuntu Family"
      when: ansible_distribution == "Ubuntu" and ansible_os_family == "Debian"

    - name: print OS 4
      debug:
        msg: "CentOS or Ubuntu"
      when: ansible_distribution == "CentOS" or ansible_distribution == "Ubuntu"

    - name: print OS 5
      debug:
        msg: "Ubuntu"
      when: ansible_distribution == "Ubuntu"
