-
  name: ignore erros
  hosts: servers
  tasks:
    - name: print Hello Babes
      debug:
        msg: "Kya Bolte Public"

    - name: Print OS Name
      debug:
        msg: "{{ansible_distribution}}"
        ignore_erros: true

    - name: Print msg
      debug:
        msg: "Hello Public"