- name: Line In File and Block in file playbook
  hosts: all
  become: true
  tasks:
    - name: line-in-file
      lineinfile:
        path: /mnt/file1.conf
        regexp: "tomcat"
        line: "chage tomcat to apache"     

    - name: insert a new line 
      lineinfile:
        path: /mnt/file1.conf
        line: 'This is nginx'
        insertafter: 'nginx is a service'
        state: present

    - name: the line you want to remove
      lineinfile:
        path: /mnt/file1.conf
        line: 'httpd is a service'
        state: absent

    - name: block in file
      blockinfile:
        path: /mnt/file1.conf
        block:
          ProxyPass /sample http://localhost:8080/sample
          ProxyPassReverse /sample http://localhost/sample