- name: Line In File and Block in file playbook
  hosts: all
  become: true
  tasks:
    - name: line-in-file
      lineinfile:
        path: /mnt/file1.conf
        regexp: "tomcat"
        line: "chage tomcat to apache"     