- name: Loop
  hosts: all
  tasks:

  - name: install git, wget, vim, httpd
    package:
      name: "{{item}}"
      state: present
    become: true
    loop:
      - git
      - wget
      - vim
      - httpd
      - nginx
