- name: Install Apache web server
  hosts: servers
  become: true
  tasks:
        
    - name: Install HTTPD
      dnf:
        name: httpd
        state: present
      when: ansible_distribution == "CentOS" or ansible_os_family == "RedHat"

    - name: Install Apache2
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu" or ansible_os_family == "Debian"